// clang_frontend.cpp
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"

using namespace llvm;

int main(int argc, char **argv) {
    LLVMContext Context;
    SMDiagnostic Err;
    // Load the LLVM IR file generated by Clang
    std::unique_ptr<Module> M = parseIRFile("matrix_mult.ll", Err, Context);
    if (!M) {
        Err.print("clang_frontend", errs());
        return 1;
    }
    // Optionally run passes, optimizations, etc.
    M->print(outs(), nullptr);
    return 0;
}
